# Generated by Django 3.2.25 on 2024-05-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habilitacao',
            name='data_primeira_habilitacao',
            field=models.DateField(blank=True, null=True, verbose_name='Primeira Habilitação'),
        ),
    ]
