# Generated by Django 3.2.25 on 2024-05-12 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quarteis', '0002_alter_comandomilitar_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao', models.CharField(choices=[('Fuzil 7,62mm', 'Fuzil 7,62mm'), ('Fuzil 5,56mm', 'Fuzil 5,56mm'), ('Pistola 9mm', 'Pistola 9mm'), ('Metralhadora MAG', 'Metralhadora MAG'), ('FAP', 'FAP'), ('FAC', 'FAC'), ('Metralhadora .50', 'Metralhadora .50'), ('Fuzil 5,56mm', 'Fuzil 5,56mm'), ('Espingarda 12', 'Espingarda 12'), ('Morteiro Pesado 120mm', 'Morteiro Pesado 120mm'), ('Obuseiro 105mm', 'Obuseiro 105mm'), ('Obuseiro 155mm', 'Obuseiro 155mm'), ('Faca', 'Faca'), ('Outros', 'Outros')], default='Outros', max_length=50)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('calibre', models.CharField(blank=True, max_length=100, null=True)),
                ('fabricante', models.CharField(blank=True, max_length=100, null=True)),
                ('nr_serie', models.CharField(max_length=50, verbose_name='Número de série')),
                ('qtde_tiros', models.IntegerField(default=0, verbose_name='Quantidade de tiros')),
                ('situacao', models.CharField(choices=[('Disponível', 'Disp'), ('Indisponível', 'Insdisp'), ('Descarregado', 'Descarregado'), ('Recolhido', 'Recolhido')], default='Disponível', max_length=20)),
                ('outros_nr_serie', models.TextField(blank=True, null=True)),
                ('historico', models.TextField(blank=True, null=True)),
                ('aes', models.TextField(blank=True, null=True, verbose_name='Acessórios e Sobressalentes')),
                ('subunidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='armamento', to='quarteis.subunidade')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='armamento', to='quarteis.unidade')),
            ],
        ),
        migrations.CreateModel(
            name='Alteracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disparos', models.IntegerField(default=0, verbose_name='Disparos efetuados')),
                ('situacao', models.CharField(choices=[('Disponível', 'Disp'), ('Indisponível', 'Insdisp'), ('Descarregado', 'Descarregado'), ('Recolhido', 'Recolhido')], default='Disponível', max_length=20, verbose_name='Situação do Armamento')),
                ('data', models.DateField(auto_now=True)),
                ('alteracao', models.TextField(blank=True, null=True, verbose_name='Ocorrência observada')),
                ('armamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alteracao', to='armamentos.armamento')),
            ],
        ),
    ]
