# Generated by Django 3.2.25 on 2024-05-12 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quarteis', '0002_alter_comandomilitar_options'),
        ('armamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armamento',
            name='unidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='armamento', to='quarteis.unidade'),
            preserve_default=False,
        ),
    ]
