# Generated by Django 3.2.25 on 2024-05-19 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armamentos', '0003_alteracao_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alteracao',
            name='disparos',
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disparos', models.IntegerField(default=0, verbose_name='Disparos efetuados')),
                ('data', models.DateField(auto_now=True)),
                ('nome', models.TextField(blank=True, null=True, verbose_name='Nome da atividade')),
                ('armamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividade', to='armamentos.armamento')),
            ],
        ),
    ]
