# Generated by Django 3.2.25 on 2024-05-30 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quarteis', '0002_alter_comandomilitar_options'),
        ('armamentos', '0004_auto_20240519_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armamento',
            name='unidade',
        ),
        migrations.AlterField(
            model_name='armamento',
            name='subunidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='armamento', to='quarteis.subunidade'),
            preserve_default=False,
        ),
    ]
