# Generated by Django 3.2.23 on 2024-06-14 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_alter_habilitacao_data_primeira_habilitacao'),
        ('armamentos', '0006_manutencao'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='atirador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='atividade', to='pessoas.pessoa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alteracao',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
