# Generated by Django 3.2.23 on 2024-06-14 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armamentos', '0007_auto_20240614_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='data',
        ),
        migrations.AddField(
            model_name='atividade',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Fim da atividade'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='data_inicio',
            field=models.DateField(auto_now=True, verbose_name='Início da atividade'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='Está válido'),
        ),
        migrations.AlterField(
            model_name='alteracao',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Está vigente'),
        ),
    ]
