# Generated by Django 3.2.23 on 2024-06-15 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0001_initial'),
        ('armamentos', '0008_auto_20240614_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='atirador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atividade', to='militares.militar'),
        ),
    ]
