# Generated by Django 3.2.23 on 2024-07-07 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armamentos', '0009_alter_atividade_atirador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='is_valid',
        ),
    ]
