# Generated by Django 3.2.23 on 2024-07-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armamentos', '0010_remove_atividade_is_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da atividade'),
        ),
    ]
