# Generated by Django 3.2.23 on 2024-07-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armamentos', '0011_alter_atividade_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Início da atividade'),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
