# Generated by Django 3.2.23 on 2024-07-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armamentos', '0012_auto_20240707_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alteracao',
            name='data',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='data_inicio',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Início da atividade'),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='data',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
