# Generated by Django 3.2.25 on 2024-05-12 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quarteis', '0002_alter_comandomilitar_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao', models.CharField(choices=[('Vtr 3/4 Ton', 'Vtr 3/4 Ton'), ('Vtr 5 Ton', 'Vtr 5 Ton'), ('Vtr 7 Ton', 'Vtr 7 Ton'), ('Vtr 10 Ton', 'Vtr 10 Ton'), ('Vtr Bld', 'Vtr Bld'), ('Ambulância', 'Ambulância'), ('Vtr Adm', 'Vtr Adm'), ('Reboque Cistena', 'Reboque Cistena'), ('Vtr Cisterna', 'Vtr Cisterna'), ('Ônibus', 'Ônibus'), ('Cozinha de Campanha', 'Cozinha de Campanha'), ('Vtr Basculante', 'Vtr Basculante'), ('Outros', 'Outros')], default='Outros', max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('placa', models.CharField(blank=True, max_length=50, null=True)),
                ('ano_fabricacao', models.IntegerField(default=2000)),
                ('combustivel', models.CharField(choices=[('Gasolina', 'Gas'), ('Óleo Diesel', 'OD'), ('Álcool', 'Álcool'), ('Gasolina e Álcool', 'Flex')], default='Óleo Diesel', max_length=25)),
                ('consumo_real', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='Consumo de Combustível Real')),
                ('consumo_plan', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='Consumo de Combustível para Planejamento')),
                ('patrimonio', models.CharField(blank=True, max_length=30, null=True, verbose_name='Número de Patrimônio')),
                ('odometro', models.IntegerField(default=0)),
                ('capacidade_combustivel', models.IntegerField(default=20)),
                ('capacidade_passageiro', models.IntegerField(default=2)),
                ('situacao', models.CharField(choices=[('Disponível', 'Disp'), ('Indisponível', 'Insdisp'), ('Descarregado', 'Descarregado'), ('Recolhido', 'Recolhido')], default='Disponível', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('subunidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='viatura', to='quarteis.subunidade')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viatura', to='quarteis.unidade')),
            ],
        ),
    ]
