# Generated by Django 3.2.23 on 2024-07-06 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viaturas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ferramental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='viatura',
            name='ano_fabricacao',
        ),
        migrations.RemoveField(
            model_name='viatura',
            name='capacidade_combustivel',
        ),
        migrations.RemoveField(
            model_name='viatura',
            name='capacidade_passageiro',
        ),
        migrations.RemoveField(
            model_name='viatura',
            name='combustivel',
        ),
        migrations.RemoveField(
            model_name='viatura',
            name='consumo_plan',
        ),
        migrations.RemoveField(
            model_name='viatura',
            name='consumo_real',
        ),
        migrations.RemoveField(
            model_name='viatura',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='viatura',
            name='odometro',
        ),
        migrations.RemoveField(
            model_name='viatura',
            name='situacao',
        ),
        migrations.RemoveField(
            model_name='viatura',
            name='unidade',
        ),
        migrations.AlterField(
            model_name='viatura',
            name='classificacao',
            field=models.CharField(choices=[('Vtr 3/4 Ton', 'Vtr 3/4 Ton'), ('Vtr 1 e 1/2 Ton', 'Vtr 1 e 1/2 Ton'), ('Vtr 5 Ton', 'Vtr 5 Ton'), ('Vtr 7 Ton', 'Vtr 7 Ton'), ('Vtr 10 Ton', 'Vtr 10 Ton'), ('Vtr Bld', 'Vtr Bld'), ('Ambulância', 'Ambulância'), ('Vtr Adm', 'Vtr Adm'), ('Reboque Cistena', 'Reboque Cistena'), ('Vtr Cisterna', 'Vtr Cisterna'), ('Ônibus', 'Ônibus'), ('Cozinha de Campanha', 'Cozinha de Campanha'), ('Vtr Basculante', 'Vtr Basculante'), ('Outros', 'Outros')], default='Outros', max_length=50),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='marca',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Verificacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verificacoes', to='viaturas.viatura')),
            ],
        ),
        migrations.CreateModel(
            name='VerificacaoSituacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componente', models.CharField(max_length=50)),
                ('situacao', models.CharField(choices=[('Disponível', 'Disp'), ('Indisponível', 'Insdisp'), ('Descarregado', 'Descarregado'), ('Recolhido', 'Recolhido')], default='Disponível', max_length=20)),
                ('verificacoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verificacao_situacao', to='viaturas.verificacoes')),
            ],
        ),
        migrations.CreateModel(
            name='VerificacaoPneu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacao', models.CharField(max_length=50)),
                ('fabricacao', models.CharField(max_length=50)),
                ('verificacoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verificacao_pneu', to='viaturas.verificacoes')),
            ],
        ),
        migrations.CreateModel(
            name='VerificacaoOleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_troca', models.DateField()),
                ('verificacoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verificacao_oleo', to='viaturas.verificacoes')),
            ],
        ),
        migrations.CreateModel(
            name='VerificacaoFiltro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Combustível', 'Combustível'), ('Óleo', 'Óleo'), ('Ar', 'Ar')], default='Óleo', max_length=20)),
                ('ultima_troca', models.DateField()),
                ('verificacoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verificacao_filtro', to='viaturas.verificacoes')),
            ],
        ),
        migrations.CreateModel(
            name='ItemFerramental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('situacao', models.CharField(choices=[('Disponível', 'Disp'), ('Indisponível', 'Insdisp'), ('Descarregado', 'Descarregado'), ('Recolhido', 'Recolhido')], default='Disponível', max_length=40)),
                ('ferramental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_ferramental', to='viaturas.ferramental')),
            ],
        ),
        migrations.AddField(
            model_name='ferramental',
            name='viatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ferramental', to='viaturas.viatura'),
        ),
        migrations.CreateModel(
            name='Disponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(choices=[('Disponível', 'Disp'), ('Indisponível', 'Insdisp'), ('Descarregado', 'Descarregado'), ('Recolhido', 'Recolhido')], default='Disponível', max_length=40)),
                ('viatura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidade', to='viaturas.viatura')),
            ],
        ),
        migrations.CreateModel(
            name='DadosTecnicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo_real', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='Consumo de Combustível Real')),
                ('consumo_plan', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='Consumo de Combustível para Planejamento')),
                ('odometro', models.IntegerField(default=0)),
                ('tanque_combustivel', models.IntegerField(default=20)),
                ('tanque_oleo', models.IntegerField(default=20)),
                ('capacidade_passageiro', models.IntegerField(default=2)),
                ('chassi', models.CharField(max_length=50)),
                ('bateria', models.CharField(max_length=50)),
                ('pneu', models.CharField(max_length=50)),
                ('filtro_oleo', models.CharField(max_length=50)),
                ('filtro_ar', models.CharField(max_length=50)),
                ('filtro_combs', models.CharField(max_length=50)),
                ('tipo_oleo', models.CharField(max_length=50)),
                ('ano_fabricacao', models.IntegerField(default=2000)),
                ('combustivel', models.CharField(choices=[('Gasolina', 'Gas'), ('Óleo Diesel', 'OD'), ('Álcool', 'Álcool'), ('Gasolina e Álcool', 'Flex')], default='Óleo Diesel', max_length=25)),
                ('viatura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dados_tecnicos', to='viaturas.viatura')),
            ],
        ),
        migrations.CreateModel(
            name='Alteracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(max_length=400)),
                ('nr_os', models.CharField(blank=True, max_length=20, null=True)),
                ('valor', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('disponibilidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alteracao', to='viaturas.viatura')),
            ],
        ),
    ]
