# Generated by Django 3.2.23 on 2024-07-09 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viaturas', '0003_auto_20240707_2159'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='viatura',
            managers=[
            ],
        ),
    ]
