# Generated by Django 3.2.23 on 2024-07-09 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viaturas', '0005_verificacoes_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificacaofiltro',
            name='verificacoes',
        ),
        migrations.RemoveField(
            model_name='verificacaooleo',
            name='verificacoes',
        ),
        migrations.RemoveField(
            model_name='verificacaopneu',
            name='verificacoes',
        ),
        migrations.RemoveField(
            model_name='verificacaosituacao',
            name='verificacoes',
        ),
        migrations.AddField(
            model_name='verificacaofiltro',
            name='viatura',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='verificacao_filtro', to='viaturas.viatura'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verificacaooleo',
            name='viatura',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='verificacao_oleo', to='viaturas.viatura'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verificacaopneu',
            name='viatura',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='verificacao_pneu', to='viaturas.viatura'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verificacaosituacao',
            name='viatura',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='verificacao_situacao', to='viaturas.viatura'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemferramental',
            name='situacao',
            field=models.CharField(choices=[('Disponível', 'Disp'), ('Indisponível', 'Insdisp'), ('Inexistente', 'Inexistente')], default='Disponível', max_length=40),
        ),
        migrations.AlterField(
            model_name='verificacaosituacao',
            name='situacao',
            field=models.CharField(choices=[('Disponível', 'Disp'), ('Indisponível', 'Insdisp'), ('Inexistente', 'Inexistente')], default='Disponível', max_length=40),
        ),
        migrations.DeleteModel(
            name='Verificacoes',
        ),
    ]
