# Generated by Django 3.2.23 on 2024-07-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaturas', '0007_alter_ferramental_viatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='alteracao',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
