# Generated by Django 3.2.23 on 2024-07-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaturas', '0008_alteracao_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='alteracao',
            name='data',
            field=models.DateField(auto_now=True),
        ),
    ]
