# Generated by Django 3.2.23 on 2024-09-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaturas', '0010_auto_20240909_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadostecnicos',
            name='ano_fabricacao',
        ),
        migrations.RemoveField(
            model_name='dadostecnicos',
            name='chassi',
        ),
        migrations.RemoveField(
            model_name='dadostecnicos',
            name='odometro',
        ),
        migrations.AddField(
            model_name='viatura',
            name='ano_fabricacao',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='viatura',
            name='chassi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='viatura',
            name='odometro',
            field=models.IntegerField(default=0),
        ),
    ]
