# Generated by Django 3.2.25 on 2024-05-12 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComandoMilitar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome por Extenso', max_length=70)),
                ('abreviatura', models.CharField(max_length=40)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos')),
                ('nome_historico', models.CharField(blank=True, help_text='Nome Histórico', max_length=70, null=True)),
                ('cidade', models.CharField(blank=True, help_text='Cidade da OM', max_length=70, null=True)),
                ('estado', models.CharField(blank=True, help_text='Sigla do Estado da OM', max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrandeComando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome por Extenso', max_length=70)),
                ('abreviatura', models.CharField(max_length=40)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos')),
                ('nome_historico', models.CharField(blank=True, help_text='Nome Histórico', max_length=70, null=True)),
                ('cidade', models.CharField(blank=True, help_text='Cidade da OM', max_length=70, null=True)),
                ('estado', models.CharField(blank=True, help_text='Sigla do Estado da OM', max_length=2, null=True)),
                ('esc_sup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidade', to='quarteis.comandomilitar')),
            ],
        ),
        migrations.CreateModel(
            name='GrandeUnidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome por Extenso', max_length=70)),
                ('abreviatura', models.CharField(max_length=40)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos')),
                ('nome_historico', models.CharField(blank=True, help_text='Nome Histórico', max_length=70, null=True)),
                ('cidade', models.CharField(blank=True, help_text='Cidade da OM', max_length=70, null=True)),
                ('estado', models.CharField(blank=True, help_text='Sigla do Estado da OM', max_length=2, null=True)),
                ('esc_sup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidade', to='quarteis.grandecomando')),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome por Extenso', max_length=70)),
                ('abreviatura', models.CharField(max_length=40)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos')),
                ('nome_historico', models.CharField(blank=True, help_text='Nome Histórico', max_length=70, null=True)),
                ('cidade', models.CharField(blank=True, help_text='Cidade da OM', max_length=70, null=True)),
                ('estado', models.CharField(blank=True, help_text='Sigla do Estado da OM', max_length=2, null=True)),
                ('esc_sup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidade', to='quarteis.grandeunidade')),
            ],
        ),
        migrations.CreateModel(
            name='Subunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70, verbose_name='Nome por Extenso')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos')),
                ('abreviatura', models.CharField(default='Abreviatura da SU', max_length=40, verbose_name='Coloque a abreviatura')),
                ('nome_idt', models.CharField(blank=True, help_text='Nome de Identificação', max_length=70, null=True)),
                ('cidade', models.CharField(blank=True, help_text='Cidade da OM', max_length=70, null=True)),
                ('estado', models.CharField(blank=True, help_text='Sigla do Estado da OM', max_length=2, null=True)),
                ('esc_sup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subunidade', to='quarteis.unidade')),
            ],
        ),
    ]
