# Generated by Django 3.2.25 on 2024-05-12 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quarteis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comandomilitar',
            options={},
        ),
    ]
