# Generated by Django 3.2.23 on 2024-09-09 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('militares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia_ida', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Distância no trajeto de ida')),
                ('distancia_retorno', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Distância no trajeto de retorno')),
                ('distancia_evento', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Distância percorrida no exercício')),
                ('nome', models.CharField(max_length=100)),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField()),
                ('local', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanoEmbarque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtde_vtr', models.IntegerField(default=0)),
                ('partida', models.DateTimeField(blank=True, null=True)),
                ('chegada', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plano_embarque', to='operacoes.atividade')),
            ],
        ),
        migrations.CreateModel(
            name='PlanoEmbarqueViatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtde_passageiros', models.IntegerField(default=0)),
                ('partida', models.DateTimeField(blank=True, null=True)),
                ('chegada', models.DateTimeField(blank=True, null=True)),
                ('nr_vtr', models.IntegerField(default=1)),
                ('consumo_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('final_exc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Finalidade no Exercício')),
                ('final_dslc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Finalidade no Deslocamento')),
                ('plano_embarque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plano_embarque_vtr', to='operacoes.planoembarque')),
            ],
        ),
        migrations.CreateModel(
            name='Passageiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assento_poltrona', models.IntegerField(default=1, verbose_name='Nr Ordem do assento/poltrona')),
                ('local', models.CharField(blank=True, max_length=100, null=True, verbose_name='Localização do assento/poltrona')),
                ('militar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passageiro', to='militares.militar')),
                ('pl_emb_vrt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passageiro', to='operacoes.planoembarqueviatura')),
            ],
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('militar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motorista', to='militares.militar')),
                ('pl_emb_vrt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='motorista', to='operacoes.planoembarqueviatura')),
            ],
        ),
        migrations.CreateModel(
            name='Chefe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('militar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chefe', to='militares.militar')),
                ('pl_emb_vrt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chefe', to='operacoes.planoembarqueviatura')),
            ],
        ),
    ]
