# Generated by Django 3.2.23 on 2024-09-10 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viaturas', '0010_auto_20240909_1449'),
        ('militares', '0001_initial'),
        ('operacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planoembarqueviatura',
            name='viatura',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='plano_embarque_vtr', to='viaturas.viatura'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PlanoCarregamentoViatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.IntegerField(default=0)),
                ('pl_emb_vrt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plano_carregamento', to='operacoes.planoembarqueviatura')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(choices=[('Classe I', 'Classe I'), ('Classe II', 'Classe II'), ('Classe III', 'Classe III'), ('Classe IV', 'Classe IV'), ('Classe V', 'Classe V'), ('Classe VI', 'Classe VI'), ('Classe VII', 'Classe VII'), ('Classe VIII', 'Classe VIII'), ('Classe IX', 'Classe IX'), ('Classe X', 'Classe X')], default='Outros', max_length=50)),
                ('nome', models.CharField(max_length=100)),
                ('peso', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('pl_crgm_vrt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material', to='operacoes.planocarregamentoviatura')),
            ],
        ),
        migrations.CreateModel(
            name='Efetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='efetivo', to='operacoes.atividade')),
                ('militares', models.ManyToManyField(related_name='efetivo', to='militares.Militar')),
            ],
        ),
    ]
