# Generated by Django 3.2.23 on 2024-09-13 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quarteis', '0002_alter_comandomilitar_options'),
        ('armamentos', '0013_auto_20240709_1251'),
        ('militares', '0001_initial'),
        ('operacoes', '0002_auto_20240910_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Fuzil 7,62mm', 'Fuzil 7,62mm'), ('Fuzil 5,56mm', 'Fuzil 5,56mm'), ('Pistola 9mm', 'Pistola 9mm'), ('Metralhadora MAG', 'Metralhadora MAG'), ('FAP', 'FAP'), ('FAC', 'FAC'), ('Metralhadora .50', 'Metralhadora .50'), ('Fuzil 5,56mm', 'Fuzil 5,56mm'), ('Espingarda 12', 'Espingarda 12'), ('Morteiro Pesado 120mm', 'Morteiro Pesado 120mm'), ('Obuseiro 105mm', 'Obuseiro 105mm'), ('Obuseiro 155mm', 'Obuseiro 155mm'), ('Faca', 'Faca'), ('Outros', 'Outros')], default='Outros', max_length=50)),
                ('municao', models.BooleanField(default=False)),
                ('qtde_mun', models.IntegerField(default=0, verbose_name='Quantidade de munição')),
                ('armamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arma', to='armamentos.armamento')),
            ],
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Operacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operacional', to='operacoes.funcao')),
                ('militar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operacional', to='militares.militar')),
            ],
        ),
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='atividade',
            name='unidade',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='atividade', to='quarteis.unidade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planoembarque',
            name='atividade',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plano_embarque', to='operacoes.atividade'),
        ),
        migrations.DeleteModel(
            name='Efetivo',
        ),
        migrations.AddField(
            model_name='orgao',
            name='atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orgao', to='operacoes.atividade'),
        ),
        migrations.AddField(
            model_name='orgao',
            name='subunidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orgao', to='quarteis.subunidade'),
        ),
        migrations.AddField(
            model_name='operacional',
            name='orgao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operacional', to='operacoes.orgao'),
        ),
        migrations.AddField(
            model_name='arma',
            name='operacional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arma', to='operacoes.operacional'),
        ),
    ]
