# Generated by Django 3.2.23 on 2024-09-13 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0003_auto_20240913_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='material',
            name='pl_crgm_vrt',
        ),
        migrations.CreateModel(
            name='MaterialPlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_plano', to='operacoes.material')),
                ('pl_crgm_vrt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_plano', to='operacoes.planocarregamentoviatura')),
            ],
        ),
    ]
