# Generated by Django 3.2.23 on 2024-09-14 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0004_auto_20240913_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operacional',
            options={'ordering': ['militar__posto_grad']},
        ),
    ]
