# Generated by Django 3.2.23 on 2024-09-14 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0005_alter_operacional_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planoembarqueviatura',
            options={'ordering': ['viatura__dados_tecnicos__classificacao']},
        ),
    ]
