# Generated by Django 3.2.23 on 2024-09-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0006_alter_planoembarqueviatura_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacional',
            name='chegada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operacional',
            name='partida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
