# Generated by Django 3.2.23 on 2024-09-15 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0008_auto_20240915_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planoembarqueviatura',
            old_name='chegada',
            new_name='inicio',
        ),
        migrations.RemoveField(
            model_name='planoembarqueviatura',
            name='partida',
        ),
    ]
