# Generated by Django 3.2.23 on 2024-09-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0009_auto_20240915_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='planoembarque',
            name='retorno',
            field=models.BooleanField(default=False, verbose_name='Plano de Embarque de Retorno?'),
        ),
    ]
