# Generated by Django 3.2.23 on 2024-09-29 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0010_planoembarque_retorno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planoembarque',
            name='qtde_vtr',
        ),
    ]
