# Generated by Django 3.2.23 on 2024-09-29 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0012_remove_planoembarqueviatura_qtde_passageiros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planoembarqueviatura',
            name='consumo_total',
        ),
    ]
