# Generated by Django 3.2.23 on 2024-10-04 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0013_remove_planoembarqueviatura_consumo_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chefe',
            name='militar',
        ),
        migrations.RemoveField(
            model_name='motorista',
            name='militar',
        ),
        migrations.RemoveField(
            model_name='passageiro',
            name='militar',
        ),
        migrations.AddField(
            model_name='chefe',
            name='passageiro',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='chefe', to='operacoes.passageiro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motorista',
            name='passageiro',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='motorista', to='operacoes.passageiro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passageiro',
            name='operacional',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='passageiro', to='operacoes.operacional'),
            preserve_default=False,
        ),
    ]
