# Generated by Django 3.2.25 on 2024-05-30 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas', '0001_initial'),
        ('quarteis', '0002_alter_comandomilitar_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostoGraduacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posto_grad', models.CharField(max_length=30)),
                ('abreviatura', models.CharField(max_length=10)),
                ('codigo', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Qualificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default=0, max_length=10)),
                ('qmg', models.CharField(max_length=100)),
                ('qmp', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Militar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_guerra', models.CharField(max_length=80)),
                ('identidade', models.CharField(blank=True, max_length=30, null=True)),
                ('numero', models.CharField(blank=True, max_length=8, null=True)),
                ('data_praca', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='militar', to='pessoas.pessoa')),
                ('posto_grad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='militar', to='militares.postograduacao')),
                ('qualificacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='militar', to='militares.qualificacao')),
                ('subunidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='militar', to='quarteis.subunidade')),
            ],
        ),
    ]
