# Generated by Django 3.2.23 on 2024-09-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('militares', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='militar',
            name='prec_cp',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
