# Generated by Django 3.2.25 on 2024-05-12 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quarteis', '0002_alter_comandomilitar_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao', models.CharField(choices=[('Mun 7,62mm Comum', 'Mun 7,62mm Comum'), ('Mun 9mm', 'Mun 9mm'), ('Mun 7,62mm Tr', 'Mun 7,62mm Tr'), ('Mun .50', 'Mun .50'), ('Mun 5,56mm', 'Mun 5,56mm'), ('Mun Cal 12', 'Mun Cal 12'), ('Mun menos letal', 'Mun menos letal'), ('Gr menos letal', 'Gr menos letal'), ('Mun 120mm', 'Mun 120mm'), ('Mun 105mm', 'Mun 105mm'), ('Mun 155mm', 'Mun 155mm'), ('Outros', 'Outros')], default='Outros', max_length=50)),
                ('tipo', models.CharField(max_length=100)),
                ('lote', models.CharField(max_length=20)),
                ('quantidade', models.IntegerField(default=0)),
                ('codigo_virola', models.CharField(max_length=20)),
                ('vencimento', models.DateField(blank=True, null=True)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='municao', to='quarteis.unidade')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumoMun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField(default=0, verbose_name='Munição Consumida')),
                ('data', models.DateField(auto_now=True)),
                ('municao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumo', to='municoes.municao')),
            ],
        ),
    ]
